spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/dub
    username: root
    password: 12345
  dubbo:
    application:
      name: provider
    registry:
      address: zookeeper://127.0.0.1:2181
    protocol:
      name: dubbo
      port: 20880
    base-package: com.example.service
  mvc:
      view:
        prefix: /WEB-INF/jsp/
        suffix: .jsp

  thymeleaf:
    cache: false
    enabled: false
mybatis:
  mapper-locations: classpath:mapping/*Mapping.xml
server:
  port: 8080
http:
  maxTotal: 100
  defaultMaxPerRoute: 20
  connectTimeout: 1000
#从连接池中获取到连接的最长时间
  connectionRequestTimeout: 500
#数据传输的最长时间
  socketTimeout: 100000000
#提交请求前测试连接是否可用
  staleConnectionCheckEnabled: true

